device: cpu
pretrain_wandb: sample_auc_pretrain
train_pth: ..\..\..\data\sample\train\scaled\train_flipped_labels_0.csv
test_pth: ..\..\..\data\sample\test\scaled\test_scaled.csv
pretrain_checkpoint: ..\..\..\outputs\sample\scaled\pretrain\msk_50.ckpt
batch_size: 128
n_heads: 1
embed_dim: 200
dropout: 0.1
d_feature: 21
d_feedforward: 128
d_inter: 256
out_features: 1
masking_pct: 0.0
lr: 0.001
lr_step_size: 100
lr_gamma: 0.3
early_stop_patience: 5
n_epochs: 100
n_encoding: 5
n_decoding: 3
val_epochs: 1
downstream_pretrain: False
downstream_n_features: 21
downstream_n_final: 1
downstream_lr: 0.00001
downstream_n_epochs: 250
downstream_lr_gamma: 0.1
downstream_lr_step_size: 250
downstream_wandb: sample_auc_sft
downstream_checkpoint:  ..\..\..\outputs\sample\scaled\sft\pure_regression\
