device: cpu
pretrain_wandb: sample_pretrain_2
train_pth: ..\..\..\data\sample\train\scaled\denoised\train_flipped_labels_30.csv
test_pth: ..\..\..\data\sample\test\scaled\test_scaled.csv
batch_size: 128
n_heads: 1
embed_dim: 200
dropout: 0.1
d_feature: 21
d_feedforward: 128
d_inter: 256
out_features: 1
masking_pct: 0.3
lr: 0.001
lr_step_size: 100
lr_gamma: 0.3
early_stop_patience: 10
n_epochs: 100
n_encoding: 5
n_decoding: 3
val_epochs: 1
downstream_pretrain: True
downstream_n_features: 21
downstream_n_final: 1
downstream_lr: 0.00001
downstream_n_epochs: 250
downstream_lr_gamma: 0.1
downstream_lr_step_size: 350
downstream_wandb: sample_down_2
pretrain_checkpoint:  ..\\..\\..\\outputs\\pretrainlocal\\exp_4.ckpt
downstream_checkpoint:  ..\\..\\..\\outputs\\sftlocal\\denoised\\exp_4\\noise_30.ckpt

